### ISSUE TITLE
Model events not firing on resetAttributes.

### ISSUE THREAD

**Issue by neverthemachineforever** [NYTimes/backbone.trackit#13]
Just wondering why the internal modal attributes object is manipulated directly instead of via clear / set?
Backbone recommend that this object not be changed directly http://backbonejs.org/#Model-attributes

Currently this is affecting my model bindings via Backbone.ModelBinder as I believe it expects change events to fire.

**Comment by cipick** [comment]
resolved here: https://github.com/NYTimes/backbone.trackit/pull/10 @delambo can you please merge this pull request?

**Comment by pgifford** [comment]
Isn't this the point of trackit?  I find trackit useful precisely because it doesn't fire a change event with every attribute change.

**Comment by delambo** [comment]
merged #10
